ДЗ 1
MFaceLess/2024-2-VK-EDU-Frontend-M-Gilev pull request #1
Opened 2024-09-23 05:46 UTC by MFaceLess

# Домашнее задание №1

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
1) Написаны код для функций convertBytesToHuman.js, correctSentence.js, nonUniqueElements.js
2) После реализации всех трех функций, написан тест на функцию convertBytesToHuman

2024-09-23 11:12 UTC, sh4rkizz requested changes
Следует также добавить преподов в `asingee`/`reviewers`, согласно инструкции сдачи домашек

2024-09-23 11:12 UTC, sh4rkizz commented on convertBytesToHuman.js
> +  ]);
эту Map можно без каких-либо рисков заменить на стандартный массив, ведь индексы которые захардкожены совпадают, предлагаю поменять

2024-09-23 11:12 UTC, sh4rkizz commented on convertBytesToHuman.test.js
> +});
Стоит добавить сломанных типов данных
например бесконечность, объект, массив, функцию, NaN

что-то из этого гарантированно даст ошибочный результат

2024-09-23 11:12 UTC, sh4rkizz commented on nonUniqueElements.js
> +  return result;
В целом использование дополнительного массива ничем не обусловлено, поскольку можно фильтровать исходных массив с помощью встроенных функций

2024-09-23 11:12 UTC, sh4rkizz commented on convertBytesToHuman.js
> +  }
По идее, нужно вернуть `false`, в случае некорректного ввода

2024-09-23 15:34 UTC, MFaceLess commented
@sh4rkizz Исправил замечания

2024-09-23 15:56 UTC, sh4rkizz approved these changes
lgtm

2024-09-25 21:04 UTC, martinkomitsky approved these changes
12!

2024-09-25 21:04 UTC, merged