HW10
MFaceLess/2024-2-VK-EDU-Frontend-M-Gilev pull request #10
Opened 2024-11-28 17:38 UTC by MFaceLess

# Домашнее задание № 10

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
1) Добавлены формы регистрации
2) Добавлена форма для входа в платформу
*

2024-11-30 13:36 UTC, sh4rkizz requested changes

2024-11-30 13:36 UTC, sh4rkizz commented on react-chat/src/components/auth-form/index.jsx
>  import React, { forwardRef, useEffect, useState } from 'react';
В рамках этой домашки надо проработать редиректы на страницу авторизации, если нет токенов
О чем я говорю:
\- захожу на страницу чата по авторизованным пользователем, 
\- пробиваю localStorage.clear() в консоль
\- обновляю страницу

После этого ожидаю, что меня бросит на страницу /auth, а в реальности ломается интерфейс, потому что ему не хватило данных [из-за 401]



<img width="434" alt="изображение" src="https://github.com/user-attachments/assets/7cb2e70d-c11d-445b-a655-ab4b543c7ad6">

<img width="913" alt="изображение" src="https://github.com/user-attachments/assets/60dea652-9e84-42de-ac79-530fc1b3dbbf">

2024-11-30 13:36 UTC, sh4rkizz commented on react-chat/src/components/auth-form/index.jsx
>  import React, { forwardRef, useEffect, useState } from 'react';
Со страницы со списком чатов должен быть безусловный редирект, alert, который говорит пользователю что произошло в целом не нужен, но можно и сообщить что авторизация сдохла 
[см.  следующий коммент]

2024-11-30 13:36 UTC, sh4rkizz commented on react-chat/src/components/auth-form/index.jsx
>  import React, { forwardRef, useEffect, useState } from 'react';
Alert-ы выглядит дешево и сильно раздражает, потому что требует дополнительный клик, чтобы закрыть

Предлагаю воспользоваться либой react-toastify для отображения пользовательских ошибок / нотификаций

<img width="459" alt="изображение" src="https://github.com/user-attachments/assets/454534a3-2ed3-4d45-8ebb-ab2fcfd2cc16">

2024-11-30 13:36 UTC, sh4rkizz commented on react-chat/src/components/auth-form/index.jsx
>  import React, { forwardRef, useEffect, useState } from 'react';
Под зарегом я НЕ должен иметь возможности попадать на `/auth` или `/register`,
Под незарегом я НЕ должен иметь возможности попадать на любую страницу кроме `/register` или `/auth`

Нужно проработать защищенные урлы

2024-11-30 13:36 UTC, sh4rkizz commented on react-chat/src/components/auth-form/index.jsx
>  import React, { forwardRef, useEffect, useState } from 'react';
Ошибки нужно выводить под полем

<img width="445" alt="изображение" src="https://github.com/user-attachments/assets/b1ae3c8c-2d48-4a9e-a197-5e2db9f3b95e">


существует базово четыре типа возвращаемых ошибок

1. Пользователь делает что-то явно не так, потому что глупый и не читает подсказки
2. Пользователь делает что-то, но он не специально
3. Пользователь пытается нас сломать
4. Серверу больно

первый тип ошибок возвращается как правило в форме, зависимо от фреймворка это может быть по-разному, но базово - словарь ключ-значение: где ключ - имя поля формы, значение - ошибка
такие ошибки нужно обабатывать красненьким текстом под полем
сбрасывать ошибку поля - при вводе в это поле

второй тип это второй уровень валидации, например, что чат уже создан или чел залил слишком большой файл или самое частое - пароль+логин неверны
возвращается либо по ключу формы либо по одному из ключей: `__all__`, `detail`, `non_field_errors`
если ключ формы - выводить под полем [сбрасывать при его изменении]
если один из трех generic-ключей - выводить около кнопки "сохранить" или где-то в интерфейсе [сбрасывать при вводе в любое поле], а можно и в тостифай сунуть, как удобно

третий тип это например когда чувак отправил слишком много запросов [429 код], или nginx не может скушать файл [413 код]
возвращается как правило по особому ключу или без ключа [и тогда смотрят код ответа]
однозначно тостифай

четвертый тип это 5хх ошибки, когда либо бекендер сделал плохо, либо сервис под большой нагрузкой и грустит
однозначно тостифай

2024-11-30 13:36 UTC, sh4rkizz commented on react-chat/src/components/auth-form/index.jsx
>  import React, { forwardRef, useEffect, useState } from 'react';
Предлагаю сделать какую-то заглушку для чата, когда он пуст [нет сообщений]

<img width="848" alt="изображение" src="https://github.com/user-attachments/assets/4889a3db-7141-4ba5-888c-9140114b01a2">

2024-11-30 13:36 UTC, sh4rkizz commented on react-chat/src/components/auth-form/index.jsx
>  import React, { forwardRef, useEffect, useState } from 'react';
Я должен иметь возможность сделать `logout`
Метод должен чистить токены и возвращать меня на страницу `auth`

Предлагаю добавить отдельной кнопкой в выпадающее меню

2024-12-02 21:28 UTC, sh4rkizz requested changes

2024-12-02 21:28 UTC, sh4rkizz commented on react-chat/package.json
>    "devDependencies": {
Тык в эту кнопку меня на доли секунды забросит на #/, а потом выкинет обратно
Естественно с морганием интерфейса

По идее с страницы `login` НАЗАД уйти некуда, соответственно и кнопка не нужна

<img width="360" alt="изображение" src="https://github.com/user-attachments/assets/9e59a719-9934-4924-af3e-1b43415efc85">

2024-12-02 21:28 UTC, sh4rkizz commented on react-chat/src/App.jsx
>        <HashRouter>
Проверять route нужно на этом уровне 
[сейчас если попытаться перейти на страницу чатов незарегом будет моргать страница - это крит]

Стоит завести компонент-обертку `PrivateRoute`
Внутри проверять наличие токенов, если они отсутствуют [или доработав - протухли]
return <Navigate to="/login" replace />;

Иначе `return childen`

Важно понимать, что `children` в данном случае передается в `PrivateRoute` как компонент примерно следующим образом:
```
<PrivateRoute>
    <Profile />
</PrivateRoute>
```


Тогда полный элемент внутри HashRouter выглядит так
```
<Route
  path="/profile"
  element={
    <PrivateRoute>
      <Profile />
    </PrivateRoute>
  }
/>
```

Аналогично, через условно похожий `PublicRoute` делается обертка для auth/register страниц

2024-12-02 21:28 UTC, sh4rkizz commented on react-chat/src/App.jsx
>        <HashRouter>
Это так же позволит избежать лишних запросов 
[когда они 100% дадут 401, потому что токен отсутствует]

<img width="503" alt="изображение" src="https://github.com/user-attachments/assets/99762baa-f1b9-4faa-978c-0c3a2972e8fe">

2024-12-02 21:28 UTC, sh4rkizz commented on react-chat/src/App.jsx
>        <HashRouter>
Давай в рамках 11 ДЗ

сейчас сервер бекенда отдает 500 на удаление профиля, значит самое время обработать ошибки
Каждый блок catch должен выводить что что-то пошло не так [toastify, если 5xx ошибка] 

<img width="709" alt="изображение" src="https://github.com/user-attachments/assets/d166d05f-d896-48bc-9925-047ded6dc28a">

2024-12-02 21:28 UTC, sh4rkizz commented on react-chat/src/App.jsx
>        <HashRouter>
301 код и повторный запрос, потому что каждая основная часть URL, по которому приложение стучится, должно завершаться `/`

`DELETE 301 https://vkedu-fullstack-div2.ru/api/user/6dde3eb4-9355-4a8e-8cfd-3304b3871ab7`
`DELETE 500 https://vkedu-fullstack-div2.ru/api/user/6dde3eb4-9355-4a8e-8cfd-3304b3871ab7/`

2024-12-03 17:57 UTC, MFaceLess commented on react-chat/src/App.jsx
>        <HashRouter>
Исправил замечения

2024-12-03 22:32 UTC, sh4rkizz approved these changes
lgtm!

2024-12-06 22:13 UTC, HaseProgram commented
Отлично, зачтено, 12!

2024-12-06 22:13 UTC, merged