Done exam
MFaceLess/2024-2-VK-EDU-Frontend-M-Gilev pull request #15
Opened 2024-12-23 18:12 UTC by MFaceLess

# Exam

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
1) Сделан экзамен

2024-12-29 21:04 UTC, martinkomitsky requested changes
Предварительная оценка: 36

Но уже сейчас проверять невозможно из-за огромного количества удалённый файлов из ДЗ. Непонятно, зачем это было делать. В условии сказано, что в реквесте не должно быть ничего, кроме экзамена. Нужно исправить
![image](https://github.com/user-attachments/assets/119c7f64-ff11-4495-bcb2-b75712c2df6f)

2024-12-30 07:28 UTC, MFaceLess commented
@martinkomitsky Мартин, извините за неудобства, сначала я неправильно понял - думал, что только файлы экзамена без всего залить нужно, сегодня после вашего замечания и 5 минут раздумий, я понял, что от меня хотелось, исправил замечание, спасибо за ваше терпение!

2025-01-01 20:00 UTC, martinkomitsky commented
> @martinkomitsky Мартин, извините за неудобства, сначала я неправильно понял - думал, что только файлы экзамена без всего залить нужно, сегодня после вашего замечания и 5 минут раздумий, я понял, что от меня хотелось, исправил замечание, спасибо за ваше терпение!

отлично, спасибо!

2025-01-03 00:22 UTC, HaseProgram approved these changes
Все хорошо, по коду замечаний нет, сильная работа :)

2025-01-03 00:22 UTC, HaseProgram commented on exam/src/redux/slices/langSlice.ts
> +    }
На самом деле достаточно только этого)
Хранить в сторе состояние компонентов, форм ввода точно не стоит)

2025-01-03 00:22 UTC, HaseProgram commented on exam/src/redux/slices/langSlice.ts
> +    }
46 сразу готов поставить

2025-01-03 00:23 UTC, HaseProgram approved these changes

2025-01-03 00:25 UTC, HaseProgram commented on exam/src/redux/slices/langSlice.ts
> +    }
@martinkomitsky от тебя нужен аппрув, чтобы смержить, так как ты исправления запросил

2025-01-10 12:04 UTC, martinkomitsky commented on exam/src/redux/slices/langSlice.ts
> +    }
если что, запросы на исправления можно дисмиссить)

2025-01-10 12:04 UTC, martinkomitsky approved these changes

2025-01-10 12:04 UTC, merged

2025-01-10 12:05 UTC, martinkomitsky commented
46