Done 2 homework
MFaceLess/2024-2-VK-EDU-Frontend-M-Gilev pull request #2
Opened 2024-09-30 13:40 UTC by MFaceLess

# Домашнее задание №2

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
1) Оформлена html страницы - размещены необходимые элементы по местам
2) Написаны стили для элементов
3) Написан js-код, который управляет элементами и соответствующей логикой
4) Настроен деплой страницы
![image](https://github.com/user-attachments/assets/6817f370-38e5-4c93-964b-bca5c6328f75)

2024-09-30 17:06 UTC, sh4rkizz requested changes
отписал рекомендации в лс

2024-10-01 17:17 UTC, MFaceLess commented
Исправил замечания

2024-10-02 20:01 UTC, sh4rkizz approved these changes
lgtm!

2024-10-02 20:40 UTC, HaseProgram approved these changes
Класс, 12!

2024-10-02 20:40 UTC, merged