Сделал 5-ю домашку, посылаю на проверку, вся функциональность перевед…
MFaceLess/2024-2-VK-EDU-Frontend-M-Gilev pull request #5
Opened 2024-10-26 15:44 UTC by MFaceLess

# Домашнее задание №5

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
1) Создан проект React с помощью Vite
2) Переведена вся функциональность проекта, использующего манипуляции с DOM в проект в React-style
*

2024-10-27 01:28 UTC, sh4rkizz requested changes

2024-10-27 01:28 UTC, sh4rkizz commented on react-chat/src/pages/Messanger.jsx
> +                <h2>Выберите собеседника:</h2>
думаю время пришло стилизовать эту модалку
- добавить padding
- поправить выравнивание списка
- докинуть ховеров на выбор пользователей
- поправить кнопку закрытия [скрин 2]
- сделать так, чтобы модалка закрывалась по нажатию 'Escape', по клику вне этой модалки
- было бы хорошим тоном докинуть затемняющий фон для того, что вне модалки
- запретить скролл вне модалки [когда она открыта] - поможет overflow: hidden для body, когда модалка открыта

<img width="373" alt="изображение" src="https://github.com/user-attachments/assets/5d35dca3-09dd-41d1-a383-17b397467963">

<img width="389" alt="изображение" src="https://github.com/user-attachments/assets/875548ff-4ce5-4818-837e-f2035acc053d">

2024-10-27 01:28 UTC, sh4rkizz commented on react-chat/src/pages/Messanger.jsx
> +                  </li>
Давай поправим скролл при длинном тексте
<img width="840" alt="изображение" src="https://github.com/user-attachments/assets/b66503a6-961b-4966-a8e1-d87aa14a3b22">

2024-10-27 01:28 UTC, sh4rkizz commented on react-chat/src/pages/Messanger.jsx
> +                  </li>
Так же предлагаю декомпозировать код, как показано в домашке
хотелось бы увидеть огранизацию примерно такого образа внутри `src/` [можно дополнять]

```
components /
    chat-send-message-form /
        index.css - стили для компонента
        index.jsx - файл с компонентом формы для отправки сообщения [только для страницы чата]
    chat-message / 
        index.css - стили для компонента
        index.jsx - файл с компонентом сообщения [только для страницы чата]
    header /
        HeaderChatList.css
        HeaderChatList.jsx

        HeaderChatList.css
        HeaderChat.jsx

        index.jsx - файл внутри которого будет прописано [чтобы экспорт был удобным и корректным]:
                export { HeaderChatList } from "./HeaderChatList.jsx"
                export { HeaderChat } from "./HeaderChat.jsx"    

pages /
    chat /
        index.css - файл с основными стилями страницы чата [если потребуются]
        index.jsx - файл со страницей чата
    messenger /
        index.css - файл с основными стилями страницы чата [если потребуются]
        index.jsx - файл со страницей списка чатов
```

Предлагаю компоненты в директории `components/` оставлять `export const`, а страницы в `pages/` делать `export default const`

2024-10-27 01:28 UTC, sh4rkizz commented on react-chat/src/pages/Messanger.jsx
> +import './Messanger.css';
Заметил очепятку `Messanger` -> `Messenger` [по всему проекту]
давай поправим)

2024-10-27 01:28 UTC, sh4rkizz commented on react-chat/src/pages/Messanger.css
> +.header {
Давай поправим шрифты, и стили для мобильного хедера, было бы классно его высоту так же уменьшить
<img width="516" alt="изображение" src="https://github.com/user-attachments/assets/5939d49c-0ce4-4f2a-b659-0dae6d73b234">

2024-10-27 01:28 UTC, sh4rkizz commented on react-chat/src/pages/Chat.jsx
> +  );
Немного не react-way, как раз такое стоит выносить в отдельные компоненты

2024-10-27 01:28 UTC, sh4rkizz commented on react-chat/src/pages/Messanger.jsx
> +                  </li>
немного больно что она овальная, а не кругленькая
давай поправим, пожалуйста)
<img width="289" alt="изображение" src="https://github.com/user-attachments/assets/aa8f1c95-b9f5-4e0b-be87-e7d871b321dd">

2024-10-27 01:31 UTC, sh4rkizz commented on react-chat/src/pages/Chat.jsx
> +  );
давай отключим автокомплит на форме, он в мессенджерах излишен

<img width="1440" alt="изображение" src="https://github.com/user-attachments/assets/97885da7-663c-4751-8462-5a35a96d2ec0">

2024-10-27 16:16 UTC, MFaceLess commented
Исправил замечения

2024-10-28 16:47 UTC, sh4rkizz approved these changes
lgtm

2024-10-31 06:26 UTC, HaseProgram approved these changes
Отлично, 10!

2024-10-31 06:26 UTC, merged