06
MFaceLess/2024-2-VK-EDU-Frontend-M-Gilev pull request #6
Opened 2024-10-30 17:31 UTC by MFaceLess

# Домашнее задание №6

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
1) Настроен React-роутинг
2) Сверстана страница редактирования профиля

2024-10-30 22:50 UTC, sh4rkizz requested changes

2024-10-30 22:50 UTC, sh4rkizz commented on react-chat/src/pages/messenger/index.jsx
> +                <h2>Выберите собеседника:</h2>
Давай прокачаем эту модалку дальше
Фокусируемая на скрине область - пространство, котрое кликабельно, нужно бы его растянуть

<img width="328" alt="изображение" src="https://github.com/user-attachments/assets/a32176c3-f6f5-4454-82d6-b971529f67c7">


Вместо `border-bottom` для `#chatList li` предлагаю `border-top` для `#chatList li + #chatlist li` [уберет черточку под последним элементом]
<img width="284" alt="изображение" src="https://github.com/user-attachments/assets/4e2cd54b-8760-44f6-af93-b410fc36108c">

2024-10-30 22:50 UTC, sh4rkizz commented on react-chat/src/components/burger-side-menu/index.jsx
> +    const [burgerMenuItems, setBurgerMenuItems] = useState(['Страница профиля']);
Давай стилизуем чутка менюшку
уберем подчеркивание, точку слева, назовем это "профиль", увеличим шрифт, + что-то на твое усмотрение

<img width="251" alt="изображение" src="https://github.com/user-attachments/assets/1d18c4f8-ecce-4e96-aa58-7b4fcd3dbb58">

2024-10-30 22:50 UTC, sh4rkizz commented on react-chat/src/components/burger-side-menu/index.jsx
> +    const [burgerMenuItems, setBurgerMenuItems] = useState(['Страница профиля']);
на мобилке эта штука выползает на экран

<img width="154" alt="изображение" src="https://github.com/user-attachments/assets/3c95d3fe-035d-44b9-be23-838dadc48c08">

2024-10-30 22:50 UTC, sh4rkizz commented on react-chat/src/components/header/HaderProfilePage.jsx
> +            </button>
стоит название класса поменять, все-таки это не searc-icon

<img width="591" alt="изображение" src="https://github.com/user-attachments/assets/00267b26-84df-4561-8bb5-74b6ad01b130">

2024-10-30 22:50 UTC, sh4rkizz commented on react-chat/src/components/header/HaderProfilePage.jsx
> +            </button>
Самая важная часть - нужно добавить сохранение данных в профиле по нажатии на эту кнопку

2024-10-30 22:50 UTC, sh4rkizz commented on react-chat/src/components/header/HeaderChat.jsx
> +};
Предлагаю использовать хедер, который появляется при мобильной ширине для чата 
[взять высоту из него] - сейчас на ПК излишне большой хедер

а также попередвигать его компоненты
используй для этого display: flex и его настройки
хотелось бы, чтобы получилось ровнее

<img width="563" alt="изображение" src="https://github.com/user-attachments/assets/a03a7e39-0bac-48a3-8660-1051542859c7">

2024-10-30 22:50 UTC, sh4rkizz commented on react-chat/src/App.jsx
> +    </HashRouter>
Пока не ясно куда эта ссылка ведет, предлагаю временно ее спилить
<img width="488" alt="изображение" src="https://github.com/user-attachments/assets/cbbef6eb-d688-4da8-a0f8-3d524ae382d4">

2024-11-03 09:53 UTC, sh4rkizz approved these changes
lgtm

2024-11-03 09:59 UTC, sh4rkizz approved these changes
lgtm

2024-11-03 10:02 UTC, sh4rkizz approved these changes
апрув

2024-11-05 09:19 UTC, merged

2024-11-05 09:19 UTC, martinkomitsky commented
12!