07
MFaceLess/2024-2-VK-EDU-Frontend-M-Gilev pull request #7
Opened 2024-11-07 18:16 UTC by MFaceLess

# Домашнее задание №7

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
1) Подключен бэкэнд
*
*

2024-11-10 21:10 UTC, sh4rkizz requested changes

2024-11-10 21:10 UTC, sh4rkizz commented on react-chat/src/pages/chat/index.jsx
> +      alert('Чат успешно создан!');
Когда нет сообщений, этот `badge` наверно не нужен

<img width="1012" alt="изображение" src="https://github.com/user-attachments/assets/3e457161-0c1a-4ac5-929a-1dfde34bfc69">

2024-11-10 21:10 UTC, sh4rkizz commented on react-chat/src/pages/chat/index.jsx
> +      alert('Чат успешно создан!');
Длинный текст вываливается за границы экрана

<img width="803" alt="изображение" src="https://github.com/user-attachments/assets/a2d09b22-b724-4c70-b822-b64be274e01e">

2024-11-10 21:10 UTC, sh4rkizz commented on react-chat/src/pages/chat/index.jsx
> +      alert('Чат успешно создан!');
Хотелось бы чтобы сообщения не были в упор к шапке и границам
Предлагаю добавить `padding` на элемент списка сообщений

<img width="358" alt="изображение" src="https://github.com/user-attachments/assets/13d1f3f0-6363-45a2-896b-330d91f83c6b">

2024-11-10 21:12 UTC, sh4rkizz commented on react-chat/src/pages/chat/index.jsx
> +      alert('Чат успешно создан!');
Случайно заметил и теперь не отпускает
Картинка не выровнена по центру

<img width="372" alt="изображение" src="https://github.com/user-attachments/assets/f97de558-135b-4859-81cd-69fead2c20c9">

2024-11-10 21:13 UTC, sh4rkizz commented on react-chat/src/pages/chat/index.jsx
> +      alert('Чат успешно создан!');
Кнопки футера кликабельны даже вне визуальной области

<img width="315" alt="изображение" src="https://github.com/user-attachments/assets/0b9b5a4d-abfc-4154-bc94-f64a79f291f1">

2024-11-11 15:14 UTC, MFaceLess commented
Исправил замечания

2024-11-11 15:22 UTC, sh4rkizz approved these changes
lgtm!

2024-11-15 09:56 UTC, merged