08
MFaceLess/2024-2-VK-EDU-Frontend-M-Gilev pull request #8
Opened 2024-11-14 17:42 UTC by MFaceLess

# Домашнее задание № 8

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
1) Добавлена Geolocation API
2) Проработана логика посылки изображений
3) Проработана логика посылки голосовых сообщений

2024-11-14 22:46 UTC, sh4rkizz requested changes

2024-11-14 22:46 UTC, sh4rkizz commented on react-chat/src/App.jsx
>      </HashRouter>
Давай уберем этот эффект от нажатия, смотрится странно

<img width="816" alt="изображение" src="https://github.com/user-attachments/assets/034aa7dd-2f20-407b-9b25-c4569e36e139">

<img width="816" alt="изображение" src="https://github.com/user-attachments/assets/2413eae6-4d26-45a6-9f77-76bc566ea55b">

2024-11-14 22:46 UTC, sh4rkizz commented on react-chat/src/App.jsx
>      </HashRouter>
не понятно как отправить фотографию, еще в разработке?

при нажатии ее можно выбрать, но при этом ни одна известная комбинация клавиш и кнопок интерфейса ее не отправляет

еще странно, что если зажать эту кнопку на пару секунд, то она не срабатывает вовсе, при этом дергается нижняя часть интерфейса

<img width="211" alt="изображение" src="https://github.com/user-attachments/assets/4dace43d-1107-4b78-9d24-fa141fccb0ef">

2024-11-14 22:46 UTC, sh4rkizz commented on react-chat/src/App.jsx
>      </HashRouter>
давай добавим возможность превью этой фотографии перед отправкой, как сделано к примеру в вк

<img width="564" alt="изображение" src="https://github.com/user-attachments/assets/430dd580-5e3c-4932-b386-7293ebb936d9">

2024-11-14 22:46 UTC, sh4rkizz commented on react-chat/src/App.jsx
>      </HashRouter>
Предлагаю поработать с индикацией активной записи

Предлагаю:
- вынести voice как отдельную иконку
- при активации записи - отображать это какой-нибудь прикольной красной круглой пульсирующей штукой [посмотри референсы разных мессенджеров]
- отображать иконку отправки сообщения [конвертик], только когда есть что отправлять [будь то текст или картинка]
- если придумаешь как, хотелось бы иметь возможность отмены отправки ГС и фотографии

2024-11-14 22:46 UTC, sh4rkizz commented on react-chat/src/App.jsx
>      </HashRouter>
Давай так же доработаем использование API
Я увидел что у пользователя есть так же возможность удалить чат и удалить свой профиль

Это дорабатывается несложно, тем более что ты по срокам успеваешь, предлагаю допилить

2024-11-14 22:46 UTC, sh4rkizz commented on react-chat/src/App.jsx
>      </HashRouter>
В рамках 9 дз попрошу доработать вот этот интерфейс

1. Чтобы можно было создавать чаты с несколькими пользователями
2. Чтобы можно было находить людей для выбора [APIшка на такое есть] [[ обязательно попрошу использовать `lodash.debounce` для контроля лишних запросов к серверу]]

<img width="453" alt="изображение" src="https://github.com/user-attachments/assets/2394bb95-a758-4ae0-9c0a-0908cb85e6b8">

2024-11-14 22:46 UTC, sh4rkizz commented on react-chat/src/App.jsx
>      </HashRouter>
По фотографиям, увидел, что оно тут изменилось
<img width="322" alt="изображение" src="https://github.com/user-attachments/assets/7181688c-b53b-4f2a-8ee1-8c86189a9a78">

Но сообщение в чате с фотографией не появилось, нужно доработать)

2024-11-14 22:46 UTC, sh4rkizz commented on react-chat/src/components/chat-send-message-form/index.jsx
> +    }
как хорошее упражнение, можно декомпозировать компонент
вынести в отдельный модуль запись аудио

назвать его условно useRecorder, использовать примерно так
const [audio, setAudio, isRecording, startRecording, stopRecording] = useRecorder();

2024-11-14 22:46 UTC, sh4rkizz commented on react-chat/src/components/chats/index.jsx
> +    <div className='messages'>
Поломался на штуке, когда чат уже создан, но сообщений в нем нет [вполне валидный кейс бекенда]

<img width="459" alt="изображение" src="https://github.com/user-attachments/assets/eb9a54d6-c600-4585-a505-4844af05eadd">

2024-11-14 22:49 UTC, sh4rkizz commented
Хотелось бы, чтобы блоки сообщений отличались цветом друг от друга [мои и собеседника]

<img width="1440" alt="изображение" src="https://github.com/user-attachments/assets/70d8b0dd-117a-4363-8ee3-9c48a1525eb6">

2024-11-20 16:42 UTC, sh4rkizz submitted a review, later dismissed
огонь, молодец
lgtm

2024-11-20 16:43 UTC, sh4rkizz approved these changes
lgtm

2024-11-24 11:53 UTC, merged

2024-11-24 11:54 UTC, martinkomitsky commented
12!