09
MFaceLess/2024-2-VK-EDU-Frontend-M-Gilev pull request #9
Opened 2024-11-21 17:35 UTC by MFaceLess

# Домашнее задание №9

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
1) Используется архитектура redux
2) Подключен глобальный store в приложении
*

2024-11-21 17:54 UTC, sh4rkizz commented on react-chat/src/pages/chat/index.jsx
> +      });
Лучше выносить операции fetch в actions.js

2024-11-21 17:54 UTC, sh4rkizz commented on react-chat/src/entityes/centrifugo/index.js
> +  });
стоит handleCentrifugePush вынести в стор

2024-11-21 17:55 UTC, sh4rkizz commented on react-chat/src/redux/slices/chatSlice.js
> +            state.messages.push(action.payload);
я по доке (нетулкитовой) знаю что надо копировать объект для таких операций
типа state.messages = [...state.messages, action.payload]

иначе состояние может не измениться

2024-11-24 10:37 UTC, sh4rkizz requested changes
Предлагаю добавить лоадер

когда находишься в чате A, выходишь назад, переходишь к чату Б
на долю секунды видишь сообщения из чата А, после чего они ререндерятся

2024-11-24 10:39 UTC, sh4rkizz commented
давай имя и last seen прижмем к левому краю, чтобы они не смещали друг друга

![изображение](https://github.com/user-attachments/assets/998bdd58-63f2-4e24-a497-2cc8a9c685e3)
![изображение](https://github.com/user-attachments/assets/1970ca3b-45bf-43ea-9f46-e70e6ee4af5e)

2024-11-24 10:43 UTC, sh4rkizz commented
Предлагаю поработать с датами, нет смысла отображать полную дату, если отправлено было вчера
Стоит написать какую-нибудь утилку, которая будет собирать дату более контекстно

Возможно поможет dayjs

![изображение](https://github.com/user-attachments/assets/c7b4164a-67ff-471c-acd5-89388e95453b)
![изображение](https://github.com/user-attachments/assets/c8429742-9ba9-4fd7-93c5-de9ebb6b7c9d)

2024-11-24 10:55 UTC, sh4rkizz commented on react-chat/package.json
> +    "lodash": "^4.17.21",
lodash довольно сильно пузатит бандл
поскольку на фронте важна скорость прогрузки страницы, это ключевой фактор

лучше использовать loadsh.debounce - более легковесная утилка

2024-11-25 04:39 UTC, sh4rkizz submitted a review, later dismissed
lgtm!!

2024-11-25 04:39 UTC, sh4rkizz approved these changes
lgtm!! v2

2024-11-26 21:51 UTC, HaseProgram commented
Супер, 12!

2024-11-26 21:51 UTC, merged